List<Map<String, dynamic>> backendData = 
[
  {
    'id': 1,
    'name': 'Alice',
    'isonline':true,
    'messageType': 'text',
    'messageContent': 'Hey! How are you?',
    'arrivalTime': '08:05',
    'imageUrl': ava1,
  },
  {
    'id': 2,
    'name': 'Bob',
    'isonline':true,
    'messageType': 'video',
    'messageContent': 'Are we still meeting today?',
    'arrivalTime': '08:12',
    'imageUrl': ava1,
  },
  {
    'id': 3,
    'name': 'Charlie',
    'messageType': 'text',
    'messageContent': 'I just sent you the documents.',
    'arrivalTime': '08:18',
    'imageUrl': ava1,
  },
  {
    'id': 4,
    'name': 'Diana',
    'isonline':true,
    'messageType': 'gif',
    'messageContent': 'Thanks! I will check it out.',
    'arrivalTime': '08:25',
    'imageUrl': ava1,
  },
  {
    'id': 5,
    'name': 'Ethan',
    'isonline':false,
    'messageType': 'gif',
    'messageContent': 'Let me know if you need anything else.',
    'arrivalTime': '08:33',
    'imageUrl': ava1,
  },
  {
    'id': 6,
    'name': 'Fiona',
    'isonline':false,
    'messageType': 'text',
    'messageContent': 'I’ll call you in a bit.',
    'arrivalTime': '08:41',
    'imageUrl': ava1,
  },
  {
    'id': 7,
    'name': 'George',
    'messageType': 'text',
    'messageContent': 'Did you see my last message?',
    'arrivalTime': '08:50',
    'imageUrl': ava1,
  },
  {
    'id': 8,
    'name': 'Hannah',
    'isonline':false,
    'messageType': 'text',
    'messageContent': 'Sounds good to me 👍',
    'arrivalTime': '09:02',
    'imageUrl': ava1,
  },
  {
    'id': 9,
    'name': 'Ian',
    'isonline':true,
    'messageType': 'video',
    'messageContent': 'Running a bit late.',
    'arrivalTime': '09:10',
    'imageUrl': ava1,
  },
  {
    'id': 10,
    'name': 'Julia',
    'isonline':true,
    'messageType': 'text',
    'messageContent': 'Can you review this quickly?',
    'arrivalTime': '09:18',
    'imageUrl': ava1,
  },
  {
    'id': 11,
    'name': 'Kevin',
    'isonline':true,
    'messageType': 'text',
    'messageContent': 'Thanks for the update.',
    'arrivalTime': '09:26',
    'imageUrl': ava1,
  },
  {
    'id': 12,
    'name': 'Laura',
    'isonline':true,
    'messageType': 'video',
    'messageContent': 'Let’s sync later today.',
    'arrivalTime': '09:34',
    'imageUrl': ava1,
  },
  {
    'id': 13,
    'name': 'Mike',
    'isonline':true,
    'messageType': 'text',
    'messageContent': 'I’m on my way.',
    'arrivalTime': '09:42',
    'imageUrl': ava1,
  },
  {
    'id': 14,
    'name': 'Nina',
    'isonline':true,
    'messageType': 'video',
    'messageContent': 'Got it, thank you!',
    'arrivalTime': '09:50',
    'imageUrl': ava1,
  },
  {
    'id': 15,
    'name': 'Oscar',
    'isonline':false,
    'messageType': 'text',
    'messageContent': 'Talk to you soon.',
    'arrivalTime': '10:00',
    'imageUrl': ava1,
  },
];

String ava1 =
    "https://static.vecteezy.com/system/resources/previews/024/183/525/large_2x/avatar-of-a-man-portrait-of-a-young-guy-illustration-of-male-character-in-modern-color-style-vector.jpg";
